### ISSUE TITLE
anyone help

### ISSUE THREAD

**Issue by npmrun** [unjs/unbuild#105]
![image](https://user-images.githubusercontent.com/62639956/185018523-e1fc7ef5-53da-4c59-8818-b6d8fd1e1abf.png)
Somebody can tell me how can i resolve this? thanks!

**Comment by ScottAwesome** [comment]
You'll need to decide how to expose the API. You need to either do a default export or named exports, otherwise exports gets assigned with `default`. 

Some context: https://github.com/rollup/rollup/issues/1961

In essence, its a limitation of rollup, which has this limitation due to commonjs semantics.

**Comment by npmrun** [comment]
Thanks a lot. This is a noteworthy place.
