### ISSUE TITLE
Failed to resolve stubed module

### ISSUE THREAD

**Issue by sadeghbarati** [unjs/unbuild#438]
### Environment

Node: 18.15.0
Windows 11

### Reproduction

https://github.com/sadeghbarati/jiti-resolve-issue

### Describe the bug

Failed to resolve stub module in Windows and also macOS environment

### Additional context

I'm using `unbuild --stub` to use jiti feature in Dev mode

```ts
import jiti from "file:///D:/Sadegh/Test/unbuild-jiti-monorepo/node_modules/.pnpm/jiti@1.18.2/node_modules/jiti/lib/index.js";

/** @type {import("D:/Sadegh/Test/unbuild-jiti-monorepo/packages/lib/src/index")} */
const _module = jiti(null, { interopDefault: true, esmResolve: true })("D:/Sadegh/Test/unbuild-jiti-monorepo/packages/lib/src/index.ts");

export const test = _module.test;
```

**Comment by pi0** [comment]
original reproduction seems deleted https://github.com/unjs/unbuild/issues/438#issue-2548260002

Also please consider using mkidst/dir mode for "runtime" files that need to be stubbed and fed into a bundler like vite instead of rollup mode and jiti stubs.

If having issues with jiti stubs in Node.js runtime directly please ping me to reopen and share a minimal reproduction repository.
