### ISSUE TITLE
How to import a stub package in a Nuxt project?

### ISSUE THREAD

**Issue by jojotechs** [unjs/unbuild#447]
Hi! I encountered an issue when trying to import a workspace package (built by unbuild stub mode) in my Nuxt project during development.

The error occurs in devtools:

The requested module '/_nuxt/@fs/xxxxxx/node_modules/.pnpm/jiti@2.4.0/node_modules/jiti/dist/jiti.cjs?import&v=87bf46ed' does not provide an export named 'default' (at jiti.mjs?v=87bf46ed:2:8)
Environment:

Nuxt 3
unbuild for workspace package
jiti 2.4.0
pnpm workspace

If you have time, could you please take a look at my project: https://github.com/jojotechs/grey-parrot-i18n/blob/c4ee88da28f383f0fde70a6b1669e9b215e56e15/packages/dashboard/package.json#L17

Is this a known issue with jiti's ESM interop? Any suggestions would be appreciated.

### Additional information

- [ ] Would you be willing to help?

**Comment by pi0** [comment]
normally "runtime" output (such as vue components) should be built in mkdist mode, in this mode, stub is identical to source tree and jiti is not involved.

If you still have issues, I suggest to raise a question in [nuxt module builder](https://github.com/nuxt/module-builder) repo since it is more specific to there.
